spring:
  kafka:
    bootstrap-servers: 192.168.8.2:9092
    consumer:
      group-id: datax-agent
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer