server:
  port: 8081
  servlet:
    context-path: /datax-agent-monitor
spring:
  application:
    name: datax-agent-monitor
  profiles:
    active: dev
management:
  endpoint:
    web:
      exposure:
        include: 'loggers'
    health:
      show-details: ALWAYS
logging:
  config: classpath:log4j2.xml
