server:
  port: 8081
  servlet:
    context-path: /datax-agent-monitor
spring:
  application:
    name: datax-agent-monitor
  kafka:
    consumer:
      bootstrap-servers: 192.168.101.20:9092,192.168.101.21:9092,192.168.101.22:9092
      group-id: datax-agent-monitor
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
management:
  endpoint:
    web:
      exposure:
        include: 'loggers'
    health:
      show-details: ALWAYS
logging:
  config: classpath:log4j2.xml
