server:
  port: 8080
spring:
  application:
    name: datax-agent
  kafka:
    bootstrap-servers: 192.168.8.2:9092
    consumer:
      group-id: datax-agent
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
datax:
  home: /Users/danny_ni/Workspace/dev-tools/datax
  job:
    home: /Users/danny_ni/Workspace/dev-tools/dataxjob/scripts/
    task:
      maxRejectTimes: 3
  excutor:
    pool:
      corePoolSize: 2
      maxPoolSize: 3
  maxCheckTimes: 5
  zookeeper:
    addressAndPort: 192.168.8.2:22181


